name: triageml
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13
  - pandas
  - numpy
  - scikit-learn
  - pip
  - pip:
    - fastapi
    - uvicorn
    - pydantic
    - joblib
    - httpx
